### ISSUE TITLE
Lucida Mobile Application

### ISSUE THREAD

**Issue by knkrth** [claritylab/clarity-mobile#6]
Hi can you please provide detailed documentation on Lucida Mobile Application integrating with Lucida server?

**Comment by cdmeister** [comment]
Hello,

If you have the entire back end of Lucida all setup then, then you can install the mobile app on your phone and connect to the ip and port number of the Lucida you have running. You can send a picture, text, or speech to Lucida and get an answer back. Text is disabled but within the code you can enable text. At the moment we do not have documentation but I can definitely make one soon. If you want to get a head start, the API that we used to make the app is Apache Cordova. Essentially what it is that you use HTML/CSS/Javascript to make your app(just like a website) and the Cordova Compiler will compile the code and package it into an iOS/Android/Windows/etc app. You then manually have to install it on your device. One caveat for iOS is that you need to be running iOS 7+ and select the build target to be iOS7+ otherwise the text to speech wont work properly. We tested it with only Android and iOS. 

Thanks.

**Comment by knkrth** [comment]
thanks for your quick response
